---
- name: Install mail packages
  ansible.builtin.apt:
    name:
      - postfix
      - mailutils
      - dovecot-core
      - dovecot-imapd
      - dovecot-pop3d
      - dovecot-lmtpd
      - telnet
      - netcat-openbsd
      - dnsutils
      - rsyslog
      - dovecot-ldap
      - ldap-utils
    state: present
    update_cache: yes

- name: Deploy postfix main.cf
  ansible.builtin.template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: "0644"
  notify: Restart postfix

- name: Ensure postfix is running
  ansible.builtin.systemd:
    name: postfix
    state: started
    enabled: true

- name: Ensure dovecot is running
  ansible.builtin.systemd:
    name: dovecot
    state: started
    enabled: true

- name: Deploy dovecot 10-mail.conf
  ansible.builtin.template:
    src: 10-mail.conf.j2
    dest: /etc/dovecot/conf.d/10-mail.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart dovecot

- name: Deploy dovecot 10-auth.conf
  ansible.builtin.template:
    src: 10-auth.conf.j2
    dest: /etc/dovecot/conf.d/10-auth.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart dovecot

- name: Deploy dovecot LDAP config
  ansible.builtin.template:
    src: dovecot-ldap.conf.ext.j2
    dest: /etc/dovecot/dovecot-ldap.conf.ext
    owner: root
    group: root
    mode: "0600"
  notify: Restart dovecot
