---
- name: Deploy Samba Active Directory Domain Controller
  hosts: dc01
  become: true

  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/vault.yml
  vars:
    ad_realm: TOSS.LAN
    ad_domain: TOSS
    bootstrap_dc_host: dc02
    bootstrap_dc_ip: 192.168.0.21
    require_empty_samba_database: true


  roles:
    - samba-additional-dc
